name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 4️⃣ Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          # If GITHUB_TOKEN fails, use a PAT:
          # password: ${{ secrets.GHCR_PAT }}

      # 5️⃣ Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/node-dev-container:latest
